In [6]:
import os
import pickle

# sample

In [5]:
args = []
args.append('--input_dir /home/lucas/Desktop/kepler_str')
args.append('--output_dir /home/lucas/Desktop/output')
args.append('--dataset kepler')
args.append('--n_samples 10')
args.append('--time_window 1')
args.append('--time_step 1')
call = 'python 1.sample.py ' + ' '.join(args)
print(call)
os.system(call)

python 1.sample.py --input_dir /home/lucas/Desktop/kepler_str --output_dir /home/lucas/Desktop/output --dataset kepler --n_samples 10 --time_window 1 --time_step 1


0

In [16]:
with open('/home/lucas/Desktop/output/sample_kepler_10_1.0_1.pkl', 'rb') as f:
    d = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: '/home/lucas/Desktop/output/sample_kepler_10_1.0_1.pkl'

In [18]:
with open('/home/lucas/Desktop/tweds/twed_kepler_10_2.0_1.pkl', 'rb') as f:
    d = pickle.load(f)

In [22]:
d - d.T

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [24]:
not_nan

array([0, 1, 2])

In [25]:
df = df[not_nan]

In [26]:
time = df.iloc[:, 0].values
magnitude = df.iloc[:, 1].values

In [32]:
np.where(np.isnan(magnitude))

(array([135, 222, 280, 346, 347, 382, 404]),)

In [29]:
mag

NameError: name 'mag' is not defined

In [ ]:
vim